spring:
  batch:
    datasource:
      url: jdbc:mysql://acm-db-01.cycmo96vm8ng.ap-northeast-2.rds.amazonaws.com:3306/perfuming_batch_dev?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&DB_CLOSE_ON_EXIT=FALSE
      username: acm
<<<<<<< HEAD
      password: ENC(IPNXUg/rPLNb371777vuH6VMgjCZkAqEXXnHGNd1I1QPtVxnyge19oK+BQD99NoF)
=======
      password: ENC(IPNXUg/rPLNb371777vuH6VMgjCZkAqEXXnHGNd1I1QPtVxnyge19oK+BQD99NoF)
>>>>>>> 8be93bb (fix: rebase 마무리되지않은 부분 삭제)
