spring:
<<<<<<< HEAD
  batch:
    datasource:
      url: jdbc:mysql://acm-db-01.cycmo96vm8ng.ap-northeast-2.rds.amazonaws.com:3306/perfuming_batch_dev?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&DB_CLOSE_ON_EXIT=FALSE
      username: acm
      password: ENC(IPNXUg/rPLNb371777vuH6VMgjCZkAqEXXnHGNd1I1QPtVxnyge19oK+BQD99NoF)
=======
  datasource:
    url: jdbc:h2:file:/usr/local/var/db/h2/acm2
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  batch:
    initialize-schema: always
>>>>>>> 786108043cd515984b8573fa57103f49bd2de949
